/* eslint-disable */
// ---------------------------------------------------------
// !!! THIS FILE WAS GENERATED BY GRAPHQL-CODE-GENERATOR !!!
// !!!        DO NOT MODIFY THIS FILE BY YOURSELF        !!!
// ---------------------------------------------------------

import * as Types from './graphql/types.generated';

import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
const defaultOptions = {} as const;
export type PostTitlesQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type PostTitlesQuery = { __typename?: 'Query', posts?: Array<{ __typename?: 'Post', title: string } | null> | null };


export const PostTitlesDocument = gql`
    query PostTitles {
  posts {
    title
  }
}
    `;

/**
 * __usePostTitlesQuery__
 *
 * To run a query within a React component, call `usePostTitlesQuery` and pass it any options that fit your needs.
 * When your component renders, `usePostTitlesQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = usePostTitlesQuery({
 *   variables: {
 *   },
 * });
 */
export function usePostTitlesQuery(baseOptions?: Apollo.QueryHookOptions<PostTitlesQuery, PostTitlesQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<PostTitlesQuery, PostTitlesQueryVariables>(PostTitlesDocument, options);
      }
export function usePostTitlesLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<PostTitlesQuery, PostTitlesQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<PostTitlesQuery, PostTitlesQueryVariables>(PostTitlesDocument, options);
        }
export type PostTitlesQueryHookResult = ReturnType<typeof usePostTitlesQuery>;
export type PostTitlesLazyQueryHookResult = ReturnType<typeof usePostTitlesLazyQuery>;
export type PostTitlesQueryResult = Apollo.QueryResult<PostTitlesQuery, PostTitlesQueryVariables>;